In [3]:
import sys
#!{sys.executable} -m pip install sklearn.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [17]:

# Load scikit's random forest classifier library.
from sklearn.ensemble import RandomForestClassifier

In [139]:
# Read the initial data from the .csv -file.
data = pd.read_csv('datasets_dataset.csv')
data

ID  Week2_Quiz1  Week3_MP1  Week3_PR1  Week5_MP2  Week5_PR2  \
0     ML-2020-1         5.00       15.0        5.0      16.09       5.00   
1     ML-2020-2         3.33       15.0        5.0      17.83       5.00   
2     ML-2020-3         1.67       13.0        5.0      15.22       5.00   
3     ML-2020-4         2.50       14.0        5.0      10.00       5.00   
4     ML-2020-6         0.00       15.0        5.0      12.17       4.93   
..          ...          ...        ...        ...        ...        ...   
102  ML-2020-60         0.00        0.0        0.0       0.00       0.00   
103  ML-2020-58         0.00        0.0        0.0       0.00       0.00   
104  ML-2020-94         0.00        0.0        0.0       0.00       0.00   
105   ML-2020-9         0.00        0.0        0.0       0.00       0.00   
106  ML-2020-86         0.00        0.0        0.0       0.00       0.00   

     Week7_MP3  Week7_PR3  Week4_Quiz2  Week6_Quiz3  ...  Week7_Stat3  \
0        21.88        5.0         5.00          5.0  ...            0   
1        22.27        5.0         4.00          5.0  ...            8   
2        27.05        2.5         5.00          5.0  ...            0   
3        31.02        5.0         3.13          5.0  ...            4   
4        15.91        5.0         4.67          5.0  ...            6   
..         ...        ...          ...          ...  ...          ...   
102       0.00        0.0         0.00          0.0  ...            0   
103       0.00        0.0         0.00          0.0  ...            0   
104       0.00        0.0         0.00          0.0  ...            0   
105       0.00        0.0         0.00          0.0  ...            0   
106       0.00        0.0         0.00          0.0  ...            0   

     Week8_Stat0  Week8_Stat1  Week8_Stat2  Week8_Stat3  Week9_Stat0  \
0              5            4            0            4            8   
1              5            2            0            0           25   
2              8            2            0            0            9   
3             10            0            0            0            7   
4              8            5            1            1            5   
..           ...          ...          ...          ...          ...   
102           28            0           22            0            1   
103            0            0            0            0            3   
104            0            0            0            0            0   
105            0            0            0            0            6   
106            0            0            0            0            0   

     Week9_Stat1  Week9_Stat2  Week9_Stat3  Grade  
0              6            1            0      4  
1              3            2            5      4  
2              0            1            0      3  
3              6            0            0      3  
4              3            1            0      2  
..           ...          ...          ...    ...  
102            0            0            0      0  
103            0            0            0      0  
104            0            0            0      0  
105            0            0            0      0  
106            0            0            0      0  

[107 rows x 48 columns]

In [140]:
# Set random seed.
np.random.seed(0)

In [199]:
# Setup our dataframe.
#columns = ['Week2_Quiz1', 'Week3_MP1', 'Week3_PR1', 'Week5_MP2', 'Week5_PR2', 'Week7_MP3', 'Week7_PR3', 'Week6_Quiz3', 'Week4_Quiz2', 'Week8_Total','Grade']
columns = ['Week2_Quiz1', 'Week3_MP1', 'Week3_PR1', 'Week5_MP2', 'Week5_PR2', 'Week7_MP3', 'Week7_PR3', 'Week6_Quiz3', 'Week4_Quiz2', 'Week8_Total', 'Week1_Stat0','Week1_Stat1', 'Week2_Stat0','Week2_Stat1', 'Week3_Stat0','Week3_Stat1', 'Week4_Stat0','Week4_Stat1', 'Week5_Stat0','Week5_Stat1', 'Week6_Stat0','Week6_Stat1', 'Week7_Stat0','Week7_Stat1', 'Week8_Stat0','Week8_Stat1', 'Week9_Stat0','Week9_Stat1', 'Grade']
#columns = ['Week2_Quiz1', 'Week3_MP1', 'Week3_PR1', 'Week5_MP2', 'Week5_PR2', 'Week7_MP3', 'Week7_PR3', 'Week6_Quiz3', 'Week4_Quiz2', 'Week1_Stat0','Week1_Stat1', 'Week2_Stat0','Week2_Stat1', 'Week3_Stat0','Week3_Stat1', 'Week4_Stat0','Week4_Stat1', 'Week5_Stat0','Week5_Stat1', 'Week6_Stat0','Week6_Stat1', 'Week7_Stat0','Week7_Stat1', 'Week8_Stat0','Week8_Stat1', 'Week9_Stat0','Week9_Stat1', 'Grade']
df = pd.DataFrame(data, columns=columns)
df

Week2_Quiz1  Week3_MP1  Week3_PR1  Week5_MP2  Week5_PR2  Week7_MP3  \
0           5.00       15.0        5.0      16.09       5.00      21.88   
1           3.33       15.0        5.0      17.83       5.00      22.27   
2           1.67       13.0        5.0      15.22       5.00      27.05   
3           2.50       14.0        5.0      10.00       5.00      31.02   
4           0.00       15.0        5.0      12.17       4.93      15.91   
..           ...        ...        ...        ...        ...        ...   
102         0.00        0.0        0.0       0.00       0.00       0.00   
103         0.00        0.0        0.0       0.00       0.00       0.00   
104         0.00        0.0        0.0       0.00       0.00       0.00   
105         0.00        0.0        0.0       0.00       0.00       0.00   
106         0.00        0.0        0.0       0.00       0.00       0.00   

     Week7_PR3  Week6_Quiz3  Week4_Quiz2  Week8_Total  ...  Week5_Stat1  \
0          5.0          5.0         5.00        82.97  ...            6   
1          5.0          5.0         4.00        82.43  ...           19   
2          2.5          5.0         5.00        79.44  ...            6   
3          5.0          5.0         3.13        80.65  ...            4   
4          5.0          5.0         4.67        67.68  ...           12   
..         ...          ...          ...          ...  ...          ...   
102        0.0          0.0         0.00         0.00  ...            4   
103        0.0          0.0         0.00         0.00  ...            0   
104        0.0          0.0         0.00         0.00  ...            0   
105        0.0          0.0         0.00         0.00  ...            0   
106        0.0          0.0         0.00         0.00  ...            0   

     Week6_Stat0  Week6_Stat1  Week7_Stat0  Week7_Stat1  Week8_Stat0  \
0             28           30            2            0            5   
1             57           22           31            9            5   
2             14           20           12            4            8   
3             99           19           29            4           10   
4             22           18           43            4            8   
..           ...          ...          ...          ...          ...   
102            7           11           13            7           28   
103            0            0            0            0            0   
104            0            0            0            0            0   
105            0            0            0            0            0   
106            0            0            0            0            0   

     Week8_Stat1  Week9_Stat0  Week9_Stat1  Grade  
0              4            8            6      4  
1              2           25            3      4  
2              2            9            0      3  
3              0            7            6      3  
4              5            5            3      2  
..           ...          ...          ...    ...  
102            0            1            0      0  
103            0            3            0      0  
104            0            0            0      0  
105            0            6            0      0  
106            0            0            0      0  

[107 rows x 29 columns]

In [200]:
# Remove rows with the grade 0.
#df['Grade'] = data['Grade'].astype(int)
#df = df[df['Grade'] != 0]
#df

In [201]:
# Create a new column that for each row, generates a random number between 0 and 1, and
# if that value is less than or equal to .75, then sets the value of that cell as True
# and false otherwise. This is a quick and dirty way of randomly assigning some rows to
# be used as the training data and some as the test data.
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

# View the top 5 rows
df.head()

Week2_Quiz1  Week3_MP1  Week3_PR1  Week5_MP2  Week5_PR2  Week7_MP3  \
0         5.00       15.0        5.0      16.09       5.00      21.88   
1         3.33       15.0        5.0      17.83       5.00      22.27   
2         1.67       13.0        5.0      15.22       5.00      27.05   
3         2.50       14.0        5.0      10.00       5.00      31.02   
4         0.00       15.0        5.0      12.17       4.93      15.91   

   Week7_PR3  Week6_Quiz3  Week4_Quiz2  Week8_Total  ...  Week6_Stat0  \
0        5.0          5.0         5.00        82.97  ...           28   
1        5.0          5.0         4.00        82.43  ...           57   
2        2.5          5.0         5.00        79.44  ...           14   
3        5.0          5.0         3.13        80.65  ...           99   
4        5.0          5.0         4.67        67.68  ...           22   

   Week6_Stat1  Week7_Stat0  Week7_Stat1  Week8_Stat0  Week8_Stat1  \
0           30            2            0            5            4   
1           22           31            9            5            2   
2           20           12            4            8            2   
3           19           29            4           10            0   
4           18           43            4            8            5   

   Week9_Stat0  Week9_Stat1  Grade  is_train  
0            8            6      4     False  
1           25            3      4      True  
2            9            0      3      True  
3            7            6      3      True  
4            5            3      2      True  

[5 rows x 30 columns]

In [202]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [203]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 82
Number of observations in the test data: 25


In [204]:
# Create a list of the feature column's names
#features = df.columns[:10]
features = df.columns[:28]
#features = df.columns[:27]
features

Index(['Week2_Quiz1', 'Week3_MP1', 'Week3_PR1', 'Week5_MP2', 'Week5_PR2',
       'Week7_MP3', 'Week7_PR3', 'Week6_Quiz3', 'Week4_Quiz2', 'Week8_Total',
       'Week1_Stat0', 'Week1_Stat1', 'Week2_Stat0', 'Week2_Stat1',
       'Week3_Stat0', 'Week3_Stat1', 'Week4_Stat0', 'Week4_Stat1',
       'Week5_Stat0', 'Week5_Stat1', 'Week6_Stat0', 'Week6_Stat1',
       'Week7_Stat0', 'Week7_Stat1', 'Week8_Stat0', 'Week8_Stat1',
       'Week9_Stat0', 'Week9_Stat1'],
      dtype='object')

In [205]:
# train['Grade'] contains the actual Grades names. Before we can use it,
# we need to convert each Grade string into a digit.
#y = pd.factorize(train['Grade'])[0]
y = train['Grade'].array
# View target
y

<PandasArray>
[4, 3, 3, 2, 3, 0, 5, 4, 3, 0, 0, 5, 5, 4, 4, 4, 4, 3, 3, 0, 4, 3, 0, 0, 4, 0,
 5, 3, 0, 3, 5, 3, 4, 2, 3, 5, 4, 2, 5, 2, 0, 0, 0, 3, 4, 0, 4, 3, 0, 3, 4, 5,
 4, 4, 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0]
Length: 82, dtype: int64

In [206]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [207]:
# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
clf.predict(test[features])

array([3, 4, 4, 0, 0, 0, 3, 0, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 0, 3, 4, 0,
       0, 0, 0])

In [208]:
# View the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[0.02, 0.01, 0.44, 0.34, 0.19],
       [0.  , 0.  , 0.13, 0.46, 0.41],
       [0.01, 0.02, 0.14, 0.62, 0.21],
       [0.99, 0.  , 0.  , 0.  , 0.01],
       [0.67, 0.07, 0.22, 0.02, 0.02],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.05, 0.17, 0.45, 0.19, 0.14],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.22, 0.19, 0.47, 0.07, 0.05],
       [0.  , 0.04, 0.07, 0.36, 0.53]])

In [209]:
# Collect predictions,
preds = clf.predict(test[features])

In [210]:
# View the PREDICTED species for the first five observations
preds[0:5]

array([3, 4, 4, 0, 0])

In [211]:
# View the ACTUAL species for the first five observations
test['Grade'].head()

0     4
13    5
14    4
18    0
19    0
Name: Grade, dtype: int64

In [212]:
# Create confusion matrix
pd.crosstab(test['Grade'], preds, rownames=['Actual Grade'], colnames=['Predicted Grade'])

Predicted Grade  0  3  4  5
Actual Grade               
0                9  0  0  0
2                0  1  0  0
3                0  3  0  0
4                0  1  7  0
5                0  0  3  1

In [213]:
# View a list of the features and their importance scores
list(zip(train[features], clf.feature_importances_))

[('Week2_Quiz1', 0.01094164971007683),
 ('Week3_MP1', 0.05909644381366377),
 ('Week3_PR1', 0.06733894167542549),
 ('Week5_MP2', 0.09034139513560045),
 ('Week5_PR2', 0.022919846113050507),
 ('Week7_MP3', 0.12795047879572571),
 ('Week7_PR3', 0.01999857686356428),
 ('Week6_Quiz3', 0.040610257045490906),
 ('Week4_Quiz2', 0.06675826833188288),
 ('Week8_Total', 0.18680755705400276),
 ('Week1_Stat0', 0.014732687937530919),
 ('Week1_Stat1', 0.0),
 ('Week2_Stat0', 0.013224137898423511),
 ('Week2_Stat1', 0.0103008586897117),
 ('Week3_Stat0', 0.024192534806410537),
 ('Week3_Stat1', 0.007242859068444363),
 ('Week4_Stat0', 0.02506164288189691),
 ('Week4_Stat1', 0.01824963456848973),
 ('Week5_Stat0', 0.02426992482602258),
 ('Week5_Stat1', 0.0412089018517729),
 ('Week6_Stat0', 0.007728509834964439),
 ('Week6_Stat1', 0.01585477779859136),
 ('Week7_Stat0', 0.01655394282680799),
 ('Week7_Stat1', 0.00985709258472749),
 ('Week8_Stat0', 0.02299531092192322),
 ('Week8_Stat1', 0.014712138318828664),
 ('Week9